SELECT 
  O.ORDERID,
  O.ORDERDATE,
  O.SHIPDATE,
  O.SHIPMODE,
  O.CUSTOMERID,
  O.PRODUCTID,
  O.ORDERCOSTPRICE,
  O.ORDERSELLINGPRICE,
  C.CUSTOMERNAME,
  C.SEGMENT,
  C.COUNTRY,
  C.STATE,
  P.CATEGORY,
  P.PRODUCTNAME,
  P.SUBCATEGORY,
 (O.ORDERSELLINGPRICE - O.ORDERCOSTPRICE) AS ORDER_PROFIT
 FROM 
{{ ref('RAW_ORDER') }} AS O
LEFT JOIN 
{{ ref('RAW_CUSTOMER') }} AS C
ON O.CUSTOMERID = C.CUSTOMERID
LEFT JOIN 
{{ ref('RAW_PRODUCT') }} AS P
ON O.PRODUCTID = P.PRODUCTID