SELECT PRODUCTID,
       PRODUCTNAME,
       CATEGORY,
       SUBCATEGORY,
       SUM(ORDER_PROFIT) AS PROFIT
FROM 
    {{ ref('stg_orders') }}
    GROUP BY 
    PRODUCTID,
    PRODUCTNAME,
    CATEGORY,
    SUBCATEGORY
